version: '3.4'

services:
  update-webhook:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:80
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
